on:
  push
name: first-test
jobs:
  job-1:
    name: "List env variables"
    runs-on: ubuntu-24.04
    steps:
      - name: List env variables
        run: |
          set
          set short_sha=$(git rev-parse --short "$GITHUB_SHA")
          echo short_sha
