on:
  push
name: first-test
jobs:
  job-1:
    name: "List env variables"
    runs-on: ubuntu-24.04
    steps:
      - name: List env variables
        run: |
          set | grep "^GITHUB_"
          short_sha=$(echo $GITHUB_SHA | cut -c 1-8)
          echo GITHUB_SHA long:  $GITHUB_SHA
          echo GITHUB_SHA short: $short_sha
