on:
  push
name: first-test
jobs:
  job-1:
    name: "List env variables"
    runs-on: ubuntu-24.04
    steps:
      - name: Set short sha
        run: echo "short_sha=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_ENV
      - name: Read short sha
        run: echo ${{ env.short_sha }} 
